export const links = {
    HOTEL_REQUEST_PATH: (id) => `/hotels?hotelId=${id}`,
    MAIN_PAGE_PATH: '/',
    HOTEL_PAGE_PATH: '/hotels/:id/rooms',
    HOTEL_SEARCH_PAGE: '/hotels',
    ADMIN_PAGE: '/admin/hotels',
    HOTEL_EDIT_ID_PAGE: (id) => `/admin/hotels/${id}`,
    HOTEL_EDIT_PAGE: '/admin/hotels/:id',
    ADMIN_HOTEL_ID_PAGE: (id) => `admin/hotels/${id}/rooms`,
    HOTEL_ID_SEARCH_PAGE: (page) => `/hotels?page=${page}`,
    HOTEL_ID_PAGE: (id) => `/hotels/${id}/rooms`,
    SIGN_UP_PAGE: '/account/signup',
    SIGN_OUT_PAGE: '/account/signout',
    SIGN_IN_PAGE: '/account/login',
    USER_PAGE: '/account',
    PROFILE_PAGE: '/account/profile',
    HOTEL_LOCATIONS_LIST: '/locations',
    ALL_LOCATIONS_LIST: '/locations/all',
    SERVICE_LIST: (hotelId) => `/hotels/${hotelId}/services`,
    SERVICE_CREATION_LIST:  '/hotels/services',
    ROOM_ID_PAGE: (hotelId) => `/hotels/${hotelId}/rooms`,
    ROOM_PAGE: '/hotels/:id/rooms',
    BOOKING_PAGE: '/booking/:id',
    BOOKING_ID_PAGE: (roomId = 1) => `/booking/${roomId}`,
    HOTEL_API_PAGE: (hotelId) => `/hotels/${hotelId}`
}