export const links = {
    ABOUT_INFO_PAGE: '/about',
    HOTEL_REQUEST_PATH: (id) => `/hotels?hotelId=${id}`,
    ROOM_REQUEST_PATH: (hotelId, roomId) => `/hotels/${hotelId}/rooms?roomId=${roomId}`,
    MAIN_PAGE_PATH: '/',
    HOTEL_PAGE_PATH: '/hotels/:id/rooms',
    HOTEL_SEARCH_PAGE: '/hotels',
    ADMIN_PAGE: '/admin/hotels',
    ROOM_ID_CREATION_PAGE: (hotelId) => `/admin/new/hotels/${hotelId}/rooms`,
    ROOM_CREATION_PAGE: '/admin/new/hotels/:hotelId/rooms',
    HOTEL_CREATION_PAGE: '/admin/new/hotels',
    HOTEL_EDIT_ID_PAGE: (id) => `/admin/hotels/${id}`,
    HOTEL_EDIT_PAGE: '/admin/hotels/:id',
    ADMIN_ROOM_LIST_PAGE: '/admin/hotels/:id/rooms',
    ROOM_EDIT_PAGE: '/admin/hotels/:hotelId/rooms/:roomId',
    ROOM_ID_PAGE_PATH: (hotelId, roomId) => `/hotels/${hotelId}/rooms/${roomId}`,
    ROOM_ID_EDIT_PAGE: (hotelId, roomId) => `/admin/hotels/${hotelId}/rooms/${roomId}`,
    ADMIN_HOTEL_ID_PAGE: (id) => `/admin/hotels/${id}/rooms`,
    HOTEL_ID_SEARCH_PAGE: (page = 1) => `/hotels?page=${page}`,
    HOTEL_ID_PAGE: (id) => `/hotels/${id}/rooms`,
    SIGN_UP_PAGE: '/account/signup',
    SIGN_OUT_PAGE: '/account/signout',
    SIGN_IN_PAGE: '/account/login',
    USER_PAGE: '/account',
    PROFILE_PAGE: '/account/profile',
    HOTEL_LOCATIONS_LIST: '/locations',
    ALL_LOCATIONS_LIST: '/locations/all',
    SERVICE_LIST: (hotelId) => `/hotels/${hotelId}/services`,
    SERVICE_CREATION_LIST: '/hotels/services',
    ROOM_ID_PAGE: (hotelId) => `/hotels/${hotelId}/rooms`,
    ROOM_PAGE: '/hotels/:id/rooms',
    BOOKING_PAGE: '/booking/:id',
    BOOKING_ID_PAGE: (roomId = 1) => `/booking/${roomId}`,
    HOTEL_API_PAGE: (hotelId) => `/hotels/${hotelId}`,
    IMAGE_UPLOAD_PATH: '/images',
    IMAGE_DOWNLOAD_PATH: (imageId) => `/api/images/${imageId}`
}