export const fileConstants = {
    ADD_IMAGE_REQUEST: 'ADD_IMAGE_REQUEST',
    ADD_IMAGE_SUCCESS: 'ADD_IMAGE_SUCCESS',
    ADD_IMAGE_FAILURE: 'ADD_IMAGE_FAILURE',
    UPLOAD_FILES_REQUEST: 'UPLOAD_FILES_REQUEST',
    UPLOAD_FILES_SUCCESS: 'UPLOAD_FILES_SUCCESS',
    UPLOAD_FILES_FAILURE: 'UPLOAD_FILES_FAILURE',
    DELETE_IMAGE_REQUEST: 'DELETE_IMAGE_REQUEST'
}