export const hotelConstants = {
	GET_HOTELS_SUCCESS = 'GET_HOTELS_SUCCESS',
	GET_HOTELS_FAILURE = 'GET_HOTELS_ERROR',
	SEARCH_HOTEL_SUCCESS = 'SEARCH_HOTEL_SUCCESS',
	SEARCH_HOTEL_FAILURE = 'SEARCH_HOTEL_FAILURE',
	ADD_HOTEL_SUCCESS = 'ADD_HOTEL_SUCCESS',
	ADD_HOTEL_FAILURE = 'ADD_HOTEL_FAILURE',
	UPDATE_HOTEL_INFO_SUCCESS = 'UPDATE_HOTEL_INFO',
	UPDATE_HOTEL_INFO_FAILURE = 'UPDATE_HOTEL_INFO_FAILURE'
}