export const hotelConstants = {
    GET_HOTELS_SUCCESS: 'GET_HOTELS_SUCCESS',
    GET_HOTELS_FAILURE: 'GET_HOTELS_ERROR',
    GET_HOTELS_REQUEST: 'GET_HOTELS_REQUEST',
    SEARCH_HOTEL_SUCCESS: 'SEARCH_HOTEL_SUCCESS',
    SEARCH_HOTEL_FAILURE: 'SEARCH_HOTEL_FAILURE',
    ADD_HOTEL_SUCCESS: 'ADD_HOTEL_SUCCESS',
    ADD_HOTEL_FAILURE: 'ADD_HOTEL_FAILURE',
    UPDATE_HOTEL_INFO_SUCCESS: 'UPDATE_HOTEL_INFO',
    UPDATE_HOTEL_INFO_FAILURE: 'UPDATE_HOTEL_INFO_FAILURE',
    REMOVE_HOTEL_SUCCESS: ' REMOVE_HOTEL_SUCCESS',
    REMOVE_HOTEL_FAILURE: ' REMOVE_HOTEL_FAILURE',
    REMOVE_HOTEL_REQUEST: 'REMOVE_HOTEL_REQUEST',
    EDIT_HOTEL_SUCCESS: 'EDIT_HOTEL_SUCCESS',
    EDIT_HOTEL_FAILURE: 'EDIT_HOTEL_FAILURE',
    EDIT_HOTEL_REQUEST: 'EDIT_HOTEL_REQUEST'
}