export const reservationConstants = {
    BOOK_REQUEST: 'BOOK_REQUEST',
    BOOK_SUCCESS: 'BOOK_SUCCESS',
    BOOK_FAILURE: 'BOOK_FAILURE',
    UPDATE_REQUEST: 'UPDATE_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_FAILURE',
    ADD_SERVICE: 'ADD_SERVICE',
    REMOVE_SERVICE: 'REMOVE_SERVICE',
    GET_SERVICES_REQUEST: 'GET_SERVICES_REQUEST',
    GET_SERVICES_SUCCESS: 'GET_SERVICES_SUCCESS',
    GET_SERVICES_FAILURE: 'GET_SERVICES_FAILURE',
    SET_CURRENT_ROOM: 'SET_CURRENT_ROOM',
    SET_MOVE_IN_TIME: 'SET_MOVE_IN_TIME'
}