export const roomConstants = {
    SET_CURRENT_ROOM_PAGE: 'SET_CURRENT_ROOM_PAGE',
    SET_ADULTS: 'SET_ADULTS',
    GET_ROOMS_REQUEST: 'GET_ROOMS_REQUEST',
    GET_ROOMS_SUCCESS: 'GET_ROOMS_SUCCESS',
    GET_ROOMS_FAILURE: 'GET_ROOMS_FAILURE'
}