export const roomConstants = {
    SET_CURRENT_ROOM_PAGE: 'SET_CURRENT_ROOM_PAGE',
    SET_ADULTS: 'SET_ADULTS',
    SET_ROOM_COST: 'SET_COST',
    SET_AVAILABILITY: 'SET_AVAILABILITY',
    GET_ROOMS_REQUEST: 'GET_ROOMS_REQUEST',
    GET_ROOMS_SUCCESS: 'GET_ROOMS_SUCCESS',
    GET_ROOMS_FAILURE: 'GET_ROOMS_FAILURE',
    GET_ROOM_REQUEST: 'GET_ROOM_REQUEST',
    GET_ROOM_SUCCESS: 'GET_ROOM_SUCCESS',
    GET_ROOM_FAILURE: 'GET_ROOM_FAILURE',
    EDIT_ROOM_REQUEST: 'EDIT_ROOM_REQUEST',
    EDIT_ROOM_SUCCESS: 'EDIT_ROOM_SUCCESS',
    EDIT_ROOM_FAILURE: 'EDIT_ROOM_FAILURE'
}