export const roomConstants = {
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    GET_ROOMS_REQUEST: 'GET_ROOMS_REQUEST',
    GET_ROOMS_SUCCESS: 'GET_ROOMS_SUCCESS',
    GET_ROOMS_FAILURE: 'GET_ROOMS_FAILURE',
}