export const searchConstants = {
    GET_HOTELS_REQUEST: 'GET_HOTELS_REQUEST',
    GET_HOTELS_SUCCESS: 'GET_HOTELS_SUCCESS',
    GET_HOTELS_FAILURE: 'GET_HOTELS_FAILURE',
    SET_CURRENT_CITY: 'SET_CURRENT_CITY',
    SET_CURRENT_COUNTRY: 'SET_CURRENT_COUNTRY',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_CURRENT_HOTEL_NAME: 'SET_CURRENT_HOTEL_NAME',
    SET_START_DATE: 'SET_START_DATE',
    SET_END_DATE: 'SET_END_DATE',
    INCORRECT_DATE_ERROR: 'INCORRECT_DATE_ERROR'
}