export const searchConstants = {
    GET_HOTELS_REQUEST: 'GET_HOTELS_REQUEST',
    GET_HOTELS_SUCCESS: 'GET_HOTELS_SUCCESS',
    GET_HOTELS_FAILURE: 'GET_HOTELS_FAILURE',
    SET_CURRENT_CITY: 'SET_CURRENT_CITY',
    SET_CURRENT_COUNTRY: 'SET_CURRENT_COUNTRY',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_CURRENT_HOTEL_NAME: 'SET_CURRENT_HOTEL_NAME'
}